
/* ------------------------------------------------------------------ *
 * In-memory store (mirrors the documented PostgreSQL schema 1:1)
 * ------------------------------------------------------------------ */
const db = {
  users: [], mdts: [], callsigns: [], vehicles: [], personnel: [], sites: [],
  jobs: [], job_assignments: [], messages: [], call_requests: [],
  locations: [], emergency_events: [], audit_logs: [],
  push_subscriptions: [], patrol_schedules: [], site_visits: [], shifts: [], assets: [],
  passdown_logs: [], fuel_logs: [], asset_checkouts: [], maintenance_logs: [], beats: [],
};
const seq = {};
const nextId = (t) => (seq[t] = (seq[t] || 0) + 1);
const JOB_STATES = ['CREATED', 'DISPATCHED', 'ACKNOWLEDGED', 'EN_ROUTE', 'ON_SCENE', 'TRANSPORTING', 'COMPLETED', 'CANCELLED'];
// First time a job reaches each of these, stamp it — this is what "time
// en route" / "time on scene" is computed from client-side, with no separate
// tracking mechanism to keep in sync.
const JOB_STATUS_TS_FIELD = { DISPATCHED: 'dispatched_at', ACKNOWLEDGED: 'acknowledged_at', EN_ROUTE: 'en_route_at', ON_SCENE: 'on_scene_at', TRANSPORTING: 'transporting_at', COMPLETED: 'completed_at', CANCELLED: 'cancelled_at' };
function stampJobStatus(j, status) {
  const field = JOB_STATUS_TS_FIELD[status];
  if (field && !j[field]) j[field] = new Date().toISOString();
}

/* Scheduled site visits — a persistent, recurring patrol model distinct from
 * one-off jobs. No TRANSPORTING (nobody's being carried anywhere) but a
 * MISSED terminal state a job doesn't need: a job always starts from a human
 * deciding to create one, but a visit can be silently generated by the
 * schedule tick and then never picked up. */
const SITE_VISIT_STATES = ['SCHEDULED', 'DISPATCHED', 'ACKNOWLEDGED', 'EN_ROUTE', 'ON_SCENE', 'COMPLETED', 'CANCELLED', 'MISSED'];
const SHIFT_STATES = ['SCHEDULED', 'CONFIRMED', 'CLOCKED_IN', 'CLOCKED_OUT', 'NO_SHOW', 'CANCELLED'];
const SITE_VISIT_STATUS_TS_FIELD = { DISPATCHED: 'dispatched_at', ACKNOWLEDGED: 'acknowledged_at', EN_ROUTE: 'en_route_at', ON_SCENE: 'on_scene_at', COMPLETED: 'completed_at', CANCELLED: 'cancelled_at', MISSED: 'missed_at' };
function stampVisitStatus(v, status) {
  const field = SITE_VISIT_STATUS_TS_FIELD[status];
  if (field && !v[field]) v[field] = new Date().toISOString();
}

function haversineMeters(lat1, lon1, lat2, lon2) {
  const R = 6371000, toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1), dLon = toRad(lon2 - lon1);
  const s = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
const ON_SCENE_RADIUS_M = 100;
const EN_ROUTE_DELTA_M = 25;
/** Called from an MDT's location report. Advances a job's status without
 * anyone touching a button: ACKNOWLEDGED -> EN_ROUTE the first time the
 * reported distance to the job meaningfully decreases (actual movement
 * toward it, not GPS jitter), and either of those -> ON_SCENE once within
 * arrival radius. Deliberately does not touch TRANSPORTING/COMPLETED — those
 * stay a human decision. `assignment.last_distance_m` is the only state this
 * needs, and it's meaningless once the job is no longer being tracked, so it
 * is simply left stale rather than cleaned up.
 *
 * MDT-only for now: a driving patrol's vehicle terminal is the one thing
 * that already reports GPS on every move. A foot-patrol officer's own
 * position (once Phase C's personnel-facing terminal reports it) is a
 * natural place to extend this, not something to build ahead of that. */
function checkAutoJobProgress(mdt, lat, lon) {
  const jobId = mdt.job_id;
  if (!jobId) return;
  const j = db.jobs.find((x) => x.id === jobId);
  if (!j || j.lat == null || ['ON_SCENE', 'TRANSPORTING', 'COMPLETED', 'CANCELLED'].includes(j.status)) return;
  const a = db.job_assignments.find((x) => x.job_id === j.id && x.mdt_id === mdt.id);
  if (!a) return;
  const dist = haversineMeters(lat, lon, j.lat, j.lon);
  let newStatus = null;
  if (['ACKNOWLEDGED', 'EN_ROUTE'].includes(j.status) && dist < ON_SCENE_RADIUS_M) newStatus = 'ON_SCENE';
  else if (j.status === 'ACKNOWLEDGED' && a.last_distance_m != null && dist < a.last_distance_m - EN_ROUTE_DELTA_M) newStatus = 'EN_ROUTE';
  a.last_distance_m = dist;
  if (!newStatus) return;
  j.status = newStatus; stampJobStatus(j, newStatus); j.updated_at = new Date().toISOString();
  broadcast('job.status_changed', publicJob(j));
  logEvent('job.status_changed', `JOB ${j.reference} → ${newStatus} (auto)`, { job_id: j.id });
}
const PRIORITIES = ['RED', 'AMBER', 'GREEN', 'ROUTINE'];
const ROLES = ['SYSTEM_ADMIN', 'DISPATCHER', 'SUPERVISOR', 'FIELD_USER', 'MDT_USER'];

const { createStore } = require('./store.js');
const store = createStore(db, seq);
webpush.init(store, VAPID_SUBJECT);

/** Fire-and-forget push to a set of users' subscribed devices. Never throws —
 * a push failing must not break the REST call or WS broadcast it rides along
 * with. A 404/410 means the browser dropped the subscription; stop using it. */
function pushToUsers(userIds, payload) {
  if (!userIds.length) return;
  const subs = db.push_subscriptions.filter((s) => userIds.includes(s.user_id));
  for (const s of subs) {
    webpush.sendNotification({ endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth } }, payload)
      .then((r) => { if (r.expired) db.push_subscriptions = db.push_subscriptions.filter((x) => x.id !== s.id); })
      .catch((e) => console.warn('[webpush] send failed:', e.message));
  }
}
function pushToRoles(roles, payload) {
  pushToUsers(db.users.filter((u) => roles.includes(u.role)).map((u) => u.id), payload);
}

const findCallsign = (v) =>
  db.callsigns.find((c) => c.id === Number(v) || c.name === String(v).toUpperCase()) || null;
const findMdt = (v) =>
  db.mdts.find((m) => m.id === Number(v) || m.mdt_code === String(v).toUpperCase()) || null;
const findPersonnel = (v) =>
  db.personnel.find((p) => p.id === Number(v) || (p.employee_no && p.employee_no === String(v))) || null;

function logEvent(type, summary, data = {}) {
  const ev = { id: nextId('audit_logs'), type, summary, data, at: new Date().toISOString() };
  db.audit_logs.push(ev);
  if (db.audit_logs.length > 5000) db.audit_logs.shift();
  broadcast('event.logged', ev);
  return ev;
}
